apiVersion: v1
kind: ConfigMap
metadata:
  name: ironkv-config
  namespace: ironkv
data:
  config.toml: |
    [server]
    bind_address = "0.0.0.0"
    port = 8080
    enable_tls = false
    connection_timeout = 30

    [storage]
    engine = "memory"
    max_memory_mb = 1024
    persistence_enabled = true
    data_dir = "/app/data"

    [cluster]
    enabled = true
    node_id = "node-1"
    cluster_port = 8081
    election_timeout_ms = 1000
    heartbeat_interval_ms = 100

    [persistence]
    enabled = true
    snapshot_interval = 1000
    log_retention = 10000

    [logging]
    level = "info"
    format = "json"
    output = "stdout"

    [metrics]
    enabled = true
    port = 9090
    endpoint = "/metrics"

    [health]
    enabled = true
    port = 8080
    endpoint = "/health"
    check_interval_seconds = 30

    [security]
    enabled = true
    auth_required = false
    jwt_secret = "your-secret-key"
    session_timeout_minutes = 60

    [tls]
    enabled = false
    cert_path = "/app/certs/server.crt"
    key_path = "/app/certs/server.key"
    ca_cert_path = "/app/certs/ca.crt"
    enable_mtls = false
    auto_renewal = true
    renewal_threshold_days = 30
    check_interval_seconds = 3600
    min_tls_version = "Tls13"
    cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]
    ocsp_stapling = true
    hsts_enabled = true
    hsts_max_age = 31536000
    hsts_include_subdomains = true
    hsts_preload = false

    [cors]
    enabled = true
    allowed_origins = ["*"]
    allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
    expose_headers = []
    allow_credentials = false
    max_age = 86400

    [rate_limit]
    enabled = true
    requests_per_minute = 1000
    burst_size = 100
    window_seconds = 60
    storage_backend = "memory"
    include_headers = true

    [security_headers]
    enabled = true
    content_security_policy = "default-src 'self'"
    x_frame_options = "DENY"
    x_content_type_options = "nosniff"
    x_xss_protection = "1; mode=block"
    referrer_policy = "strict-origin-when-cross-origin"
    permissions_policy = "geolocation=(), microphone=(), camera=()"
    hsts = "max-age=31536000; includeSubDomains" 