apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironkv
  namespace: ironkv
  labels:
    app: ironkv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ironkv
  template:
    metadata:
      labels:
        app: ironkv
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: ironkv
        image: ironkv:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: RUST_BACKTRACE
          value: "1"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: config
          mountPath: /app/config.toml
          subPath: config.toml
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
        - name: certs
          mountPath: /app/certs
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
      volumes:
      - name: config
        configMap:
          name: ironkv-config
      - name: data
        persistentVolumeClaim:
          claimName: ironkv-data
      - name: logs
        emptyDir: {}
      - name: certs
        secret:
          secretName: ironkv-tls
          optional: true 