apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ironkv-data
  namespace: ironkv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 