apiVersion: v1
kind: Service
metadata:
  name: ironkv-service
  namespace: ironkv
  labels:
    app: ironkv
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: ironkv
---
apiVersion: v1
kind: Service
metadata:
  name: ironkv-external
  namespace: ironkv
  labels:
    app: ironkv
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: ironkv 