[server]
bind_address = "0.0.0.0"
port = 6379
max_connections = 10000
connection_timeout = 30
request_timeout = 5
graceful_shutdown = true
shutdown_timeout = 30

[storage]
max_memory_bytes = 2147483648  # 2GB
max_keys = 10000000
eviction_policy = "LRU"
default_ttl_seconds = 0
enable_ttl_cleanup = true
ttl_cleanup_interval = 60
ttl_cleanup_sample_size = 1000

[cluster]
enabled = true
node_id = "node2"
bind_address = "0.0.0.0"
port = 6381
heartbeat_interval = 50
failure_timeout = 150
replication_factor = 3
virtual_nodes_per_physical = 150
replication_strategy = "Asynchronous"

[cluster.members]
node1 = "127.0.0.1:6380"
node2 = "127.0.0.1:6381"
node3 = "127.0.0.1:6382"

[persistence]
enabled = true
data_dir = "/var/lib/ironkv/node2"
aof_path = "/var/lib/ironkv/node2/appendonly.aof"
snapshot_path = "/var/lib/ironkv/node2/snapshot.rdb"
enable_aof = true
snapshot_interval = 3600
max_aof_size = 104857600
enable_aof_rewrite = true

[persistence.aof_sync_policy]
Every = 1

[logging]
level = "Info"
format = "Json"
console = false
structured = true

[logging.rotation]
enabled = true
max_size = 104857600
max_files = 10
interval = "Daily"

[metrics]
enabled = true
bind_address = "0.0.0.0"
port = 9091
path = "/metrics"
prometheus = true
collection_interval = 15
histograms = true

[metrics.labels]
environment = "production"
service = "ironkv"
node = "node2"

[tracing]
enabled = true
service_name = "ironkv-node2"
service_version = "1.0.0"
sampling_rate = 0.1
opentelemetry = false
local_spans = true
max_span_duration = 60

[security]
enabled = true
tls_enabled = false
authentication_enabled = false
rate_limiting_enabled = true
rate_limit_requests_per_minute = 1000
rate_limit_burst_size = 100

[performance]
worker_threads = 8
read_buffer_size = 8192
write_buffer_size = 8192
max_connections_per_worker = 1000
connection_pool_size = 100 