pub mod store;
pub mod value;
pub mod ttl;
pub mod eviction;
pub mod persistence;
pub mod cluster;
pub mod consensus;
pub mod membership;
pub mod rebalancing;
pub mod config;
pub mod log;
pub mod metrics;
pub mod trace;
pub mod health;
pub mod security;
pub mod performance;
pub mod server;
pub mod shutdown;

pub use store::{Store, Key};
pub use value::Value;
pub use ttl::TTLStore;
pub use eviction::{EvictionStore, EvictionPolicy, EvictionConfig};
pub use persistence::{PersistenceStore, PersistenceConfig, PersistenceCommand};
pub use cluster::{ClusterManager, ClusterConfig, ClusterStatus};
pub use consensus::{RaftConsensus, RaftState, RaftRole, RaftTerm, LogEntry, LogIndex, LogTerm};
pub use membership::{MembershipManager, MembershipState, MemberInfo, MemberStatus, MembershipChange, MembershipChangeType, ChangeStatus, MembershipStats};
pub use rebalancing::{RebalancingManager, RebalancingState, RebalancingOperation, RebalancingType, RebalancingTrigger, RebalancingPlan, RebalancingStats};
pub use config::{CacheConfig, ServerConfig, StorageConfig, ClusterConfig as ConfigClusterConfig, PersistenceConfig as ConfigPersistenceConfig, LoggingConfig, MetricsConfig, TracingConfig, HealthConfig, SecurityConfig, PerformanceConfig};
pub use metrics::{MetricsCollector, MetricsSummary};
pub use health::{HealthChecker, HealthCheck, HealthStatus, HealthResponse, HealthCheckResult};
pub use security::{SecurityManager, User, Role, Permission, AuthResult, AuthzResult, AuditLogEntry};
pub use performance::{ConnectionPool, RequestBatch, PerformanceMonitor, BenchmarkResult, PerformanceReport};
pub use server::HttpServer;
pub use shutdown::{ShutdownCoordinator, ShutdownHandle, GracefulShutdownManager, ShutdownComponent, ShutdownSignal};
